<!DOCTYPE html>
<html lang>
<head>
    <title>Report Title</title>
    <!-- Add your CSS stylesheets or inline styles here -->
    <style>
        /* Add your styles for the report here */
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
        }

        h3 {
            color: #555;
            text-align: center;
        }
    </style>
</head>

<head>
    <title>This is my city >&trade;</title>
</head>
{{--
<img class="logo-img" src="logo_Option_2.png" alt="..." style="max-width: 200px; height: auto;" />
--}}

<body>
    <h1>{{$title}} </h1>
    <h3> {{$title_}}  {{ session('user_name') }}</h3>
    <p> {{$date}}</p>
    <p> Total users: {{$userNumber}}</p>
    <p> Total guides: {{$guideNumber}}</p>
    <p> Total routes: {{$routesNumber}}</p>
    <p> Total countries: {{$countriesNumber}}</p>

    <p>This report contains proprietary information and is intended solely for the use of the individual or entity to whom it is addressed. This report was generated by the admin page and contains the latest updated information in our database. Unauthorized use, disclosure, or distribution is prohibited.</p>
    <p>&copy; <?php echo date("Y"); ?> This is my city. All rights reserved.</p>

</body>

</html>
