<?php

use App\Mail\Invoice;
use App\Models\Country;
use App\Models\Guide;
use App\Models\Route;
use App\Models\User;

use PDF;

if (!function_exists('invoice')) {
    function invoice(): void
    {
        $data = [
            'title' => 'This is my city',
            'title_' => 'Report generated by',
            'date' => date('m/d/Y'),
            'userNumber' => 1,
            'guideNumber' => 1,
            'routesNumber' => 1,
            'countriesNumber' => 1
        ];

        $pdf = PDF::loadView('PDF.invoice', carContent());

        $pdfContent = $pdf->output();

        Mail::send(new Invoice( Auth::user()->email, $pdfContent));

    }
}
if (!function_exists('report_admin')) {
    function report_admin()
    {
        $userNumber = User::count();
        $guideNumber = Guide::count();
        $routesNumber = Route::count();
        $countriesNumber = Country::count();

        $data = [
            'title'=>'This is my city',
            'title_' => 'Report generated by',
            'date' => date('m/d/Y'),
            'userNumber' => $userNumber,
            'guideNumber' => $guideNumber,
            'routesNumber' => $routesNumber,
            'countriesNumber' => $countriesNumber
        ];

        $pdf = PDF::loadView('PDFreport', $data);

        return $pdf->download('report.pdf');
    }
}
