<?php

namespace App\Http\Controllers;
use App\Models\Country;
use App\Models\Guide;
use App\Models\Route;
use App\Models\User;
use Illuminate\Http\Request;
use PDF;

    class PDFController extends Controller
    {
        public function generatePDF()
        {
        $data = [
            'title' =>'Welcome to ThisIsMyCity.com',
            'date' => date('m/d/Y')
        ];

        $pdf = PDF::loadView('myPDF',$data);

        return $pdf->download('myPDF.pdf');

        }

        protected function generatePDF_report(){

            $userNumber = User::count();
            $guideNumber = Guide::count();
            $routesNumber = Route::count();
            $countriesNumber = Country::count();

            $data = [
                'title'=>'This is my city',
                'title_' => 'Report generated by',
                'date' => date('m/d/Y'),
                'userNumber' => $userNumber,
                'guideNumber' => $guideNumber,
                'routesNumber' => $routesNumber,
                'countriesNumber' => $countriesNumber
            ];

            $pdf = PDF::loadView('PDFreport', $data);

            return $pdf->download('report.pdf');
        }
    }
